#!/usr/bin/env python3
"""Regenerate data/nvidia-branches.toml from NVIDIA's per-release supportedchips.html pages.

Which Void driver package serves a GPU: the newest branch whose list contains the PCI device id.
Branches (Void package): current (nvidia), 580 (nvidia580), 470 (nvidia470), 390 (nvidia390).
Usage: tools/gen-nvidia-table.py [current_version 580_version 470_version 390_version]
"""
import re
import sys
import urllib.request

DEFAULTS = {"current": "595.104.02", "580": "580.178.04", "470": "470.256.02", "390": "390.157"}
URL = "https://download.nvidia.com/XFree86/Linux-x86_64/{v}/README/supportedchips.html"


def device_ids(version):
    html = urllib.request.urlopen(URL.format(v=version), timeout=60).read().decode("utf-8", "replace")
    # Each page lists the driver's own GPUs first, then appendix sections for GPUs that only
    # older legacy branches support (<a name="legacy_470.xx">...). Only the first part counts.
    html = html.split('<a name="legacy_', 1)[0]
    ids = set()
    # <tr id="devid2191"> or <tr id="devid2191_1028_0949"> (subsystem variants); the device id is the first part
    for m in re.finditer(r'<tr id="devid([0-9A-Fa-f]{4})', html):
        ids.add(m.group(1).lower())
    return sorted(ids)


def main():
    versions = dict(zip(DEFAULTS, sys.argv[1:5])) if len(sys.argv) >= 5 else DEFAULTS
    out = ["# Generated by tools/gen-nvidia-table.py from NVIDIA's supportedchips.html pages. Do not edit."]
    for branch, version in versions.items():
        ids = device_ids(version)
        out.append(f"\n# {branch}: driver {version}, {len(ids)} device ids")
        out.append(f'"{branch}" = [')
        for i in range(0, len(ids), 12):
            out.append("  " + ", ".join(f'"{x}"' for x in ids[i : i + 12]) + ",")
        out.append("]")
    open("data/nvidia-branches.toml", "w").write("\n".join(out) + "\n")
    print("wrote data/nvidia-branches.toml")


main()
